/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planificaicongrafica;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class Ruond extends javax.swing.JFrame {

    int contador;
    int Nproceso;
    int rafaga=0;
    int quantum=0;
    int residuorafaga=0;
    int tiempo=0;
    int barraP;
    int cantidadP;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    /**
     * Creates new form Ruond
     */
   
    public Ruond() {
        initComponents();
        txtquantum.grabFocus();
        modelo=(DefaultTableModel)jTableProceso.getModel();
        modelo2=(DefaultTableModel)jTableHistorial.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtrafaga = new javax.swing.JTextField();
        txtquantum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btniniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProceso = new javax.swing.JTable();
        pbporcentaje = new javax.swing.JProgressBar();
        txtnumero = new javax.swing.JTextField();
        txtporcentaje = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHistorial = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txttiempo = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rafaga");

        jLabel2.setText("Quantum");

        txtrafaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrafagaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Proceso");

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btniniciar.setText("Iniciar");
        btniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarActionPerformed(evt);
            }
        });

        jTableProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Rafaga", "Quantum", "Residuo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableProceso);

        jTableHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Rafaga", "Quatum", "Tiempo Final", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTableHistorial);

        jLabel4.setText("Cantidad de Proceso");

        jLabel5.setText("Tiempo de Proceso");

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pbporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txttiempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(txtcantidad, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtrafaga, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(txtquantum))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btniniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalir)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtrafaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnagregar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnsalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtquantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btniniciar))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrafagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrafagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrafagaActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        if((Integer.parseInt(txtrafaga.getText()))<=100){
            Ingresar();
            txtquantum.setEditable(false);
        }else{
            JOptionPane.showMessageDialog(null,"Las rafagas no puede ser mayor de 100");
            txtrafaga.setText(null);
            txtrafaga.grabFocus();
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed
        // TODO add your handling code here:
        new Thread(new Hilo()).start();
        Inicio();
    }//GEN-LAST:event_btniniciarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruond().setVisible(true);
            }
        });
    }
    private class Hilo implements Runnable{
        @Override
        public void run(){
            int estado=1;
            int i=0;
            while(estado!=0){
                while(i<contador){
                    cargar(i);
                    if(residuorafaga!=0 && residuorafaga>quantum){
                        for(int j=1;j<=quantum;j++){
                            jTableProceso.setValueAt("Procesando", i, 4);
                            residuorafaga--;
                            Barra(rafaga,residuorafaga);
                            Pintar();
                            jTableProceso.setValueAt(String.valueOf(residuorafaga), i, 3);
                            tiempo++;
                            Dormir();
                        }
                        jTableProceso.setValueAt("Espera",i,4);
                        if(residuorafaga==0){
                            jTableProceso.setValueAt("Terminado",i,4);
                            Pintar();
                            Informe(i);
                            Borrar(i);
                            pbporcentaje.setValue(0);
                        }
                    }else{
                        if(residuorafaga>0 && quantum!=0){
                            while(residuorafaga>0){
                                jTableProceso.setValueAt("Procesando", i, 4);
                                residuorafaga--;
                                Barra(rafaga,residuorafaga);
                                Pintar();
                                jTableProceso.setValueAt(String.valueOf(residuorafaga), i, 3);
                                tiempo++;
                                Dormir();
                            }
                            jTableProceso.setValueAt("Espera", i, 4);
                            if(residuorafaga==0&&quantum!=0){
                                jTableProceso.setValueAt("Terminado", i, 4);
                                Pintar();
                                Informe(i);
                                Borrar(i);
                                pbporcentaje.setValue(0);
                            }
                        }else{
                            if(residuorafaga==0 && quantum!=0){
                                jTableProceso.setValueAt("Terminado", i, 4);
                                Pintar();
                                Informe(i);
                                Borrar(i);
                                pbporcentaje.setValue(0);
                            }
                        }
                    }
                    txtnumero.setText(String.valueOf(""));
                    txtporcentaje.setText(String.valueOf(""));
                    i++;
                }
                i=0;
                txtnumero.setText(String.valueOf(""));
                txtporcentaje.setText(String.valueOf(""));
            }
        }
    }
    public void Ingresar(){
        //DefaultTableModel modelo = (DefaultTableModel) jTableProceso.getModel();
        contador++;
        Object[] tabla=new Object[5];
        tabla[0]=contador;
        tabla[1]=txtrafaga.getText();
        tabla[2]=txtquantum.getText();
        tabla[3]=txtrafaga.getText();
        tabla[4]="Listo";
        modelo.addRow(tabla);
        jTableProceso.setModel(modelo);
        txtrafaga.setText(null);
        txtrafaga.grabFocus();
    }
    public void cargar(int i){
        Nproceso=(int)jTableProceso.getValueAt(i, 0);
        rafaga=parseInt((String)(jTableProceso.getValueAt(i, 1)));
        quantum=parseInt((String)(jTableProceso.getValueAt(i, 2)));
        residuorafaga=parseInt((String)(jTableProceso.getValueAt(i, 3)));
        if(Nproceso>0){
            txtnumero.setText(String.valueOf(Nproceso));
        }
        
       // https://www.youtube.com/watch?v=SDempjBY4d4
    }
    public void Dormir(){
        try{
            Thread.sleep(700);
        }catch(InterruptedException ex){
            Logger.getLogger(Ruond.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    public void Informe(int i){
        //DefaultTableModel modelo2=(DefaultTableModel)jTableHistorial.getModel();
        Object[] tabla=new Object[5];
        tabla[0]=i+1;
        tabla[1]=rafaga;
        tabla[2]=quantum;
        tabla[3]=tiempo+" Segundos";
        tabla[4]="Terminado";
        modelo2.addRow(tabla);
        jTableHistorial.setModel(modelo2);
        cantidadP++;
        txtcantidad.setText((String.valueOf(cantidadP+" Terminado")));
        txttiempo.setText(String.valueOf(tiempo+ "Segundos"));
    }
    public void Borrar (int i){
        jTableProceso.setValueAt(0, i, 0);
        jTableProceso.setValueAt("0", i, 1);
        jTableProceso.setValueAt("0", i, 2);
        jTableProceso.setValueAt("0", i, 3);
        jTableProceso.setValueAt("*******", i, 4);
    }
    public void Barra(int rafaga,int Residuo){
        int Rafaga=rafaga;
        int valor=100/rafaga;
        int porcentaje=100-(valor*Residuo);
        barraP=porcentaje;
        txtporcentaje.setText(String.valueOf(barraP+"%"));
    }
    public void Pintar(){
        pbporcentaje.setValue(barraP);
        pbporcentaje.repaint();
    }
    public void Inicio(){
        txtrafaga.setVisible(false);
        txtquantum.setVisible(false);
        btnagregar.setVisible(false);
        btniniciar.setVisible(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btniniciar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHistorial;
    private javax.swing.JTable jTableProceso;
    private javax.swing.JProgressBar pbporcentaje;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtporcentaje;
    private javax.swing.JTextField txtquantum;
    private javax.swing.JTextField txtrafaga;
    private javax.swing.JTextField txttiempo;
    // End of variables declaration//GEN-END:variables
}
